version: "3.0"

services:
  mech-database:
    image: postgres:16-alpine
    container_name: mechapp-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mechapp
    ports:
      - "5555:5432"
    volumes:
      - ./backend/database/migrations:/docker-entrypoint-initdb.d
      - ./backend/database/seeds:/seeds
    # Comando para rodar o initial_data.sql como primeiro seeder
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        while ! pg_isready -U $$POSTGRES_USER; do sleep 1; done
        psql -U $$POSTGRES_USER -d $$POSTGRES_DB -f /seeds/initial_data.sql
        wait
      "
