import { StyleSheet } from 'react-native';
import { colors, globalStyles, spacing, typography } from '../../styles/globalStyles';

export const cliStyles = StyleSheet.create({
  searchContainer: {
    flexDirection: 'row',
    marginTop: spacing.large,
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    gap: spacing.small,
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.medium - 3,
    borderRadius: spacing.small,
    fontSize: typography.fontSizeText,
  },
  filterButton: {
    backgroundColor: colors.primary,
    padding: spacing.small + 2,
    borderRadius: spacing.small,
  },
  listContent: {
    paddingBottom: spacing.large,
    paddingTop: spacing.large,
    width: '100%',
    alignSelf: 'center',
  },
  avaliarButton: {
    marginTop: spacing.small,
    backgroundColor: colors.primary,
    paddingVertical: spacing.small,
    borderRadius: spacing.small / 2 + 2,
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
  },
  avaliarText: {
    color: colors.textPrimary,
    fontWeight: typography.fontWeightBold,
    fontSize: typography.fontSizeLabel,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.black_transparent,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.surface,
    padding: spacing.large,
    borderTopLeftRadius: spacing.medium,
    borderTopRightRadius: spacing.medium,
    width: '100%',
    alignSelf: 'center',
  },
  modalTitle: globalStyles.modalTitle,
  modalInput: {
    backgroundColor: colors.inputBackground,
    color: colors.textPrimary,
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small + 2,
    borderRadius: spacing.small,
    marginBottom: spacing.medium,
    width: '100%',
    alignSelf: 'center',
    fontSize: typography.fontSizeText,
  },
  modalButton: globalStyles.modalButton,
  modalButtonText: globalStyles.modalButtonText,
  card: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    padding: spacing.medium,
    borderRadius: spacing.small,
    marginBottom: spacing.medium,
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    elevation: 2,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  cardImage: {
    width: 60,
    height: 60,
    borderRadius: spacing.small,
    marginRight: spacing.medium,
  },
  cardInfo: {
    flex: 1,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: typography.fontSizeText + 1,
    fontWeight: typography.fontWeightBold,
  },
  cardSubtitle: {
    color: colors.textHint,
    marginTop: spacing.small / 2,
    fontSize: typography.fontSizeLabel,
  },
  cardRating: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 50,
  },
  ratingText: {
    color: colors.gold,
    fontWeight: typography.fontWeightBold,
    marginTop: spacing.small / 4,
    fontSize: typography.fontSizeLabel,
  },
  noRating: {
    color: colors.textLabel,
    fontSize: typography.fontSizeLabel - 2,
    textAlign: 'center',
  },
  placeholderImage: {
    width: 60,
    height: 60,
    borderRadius: spacing.small,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.medium,
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xlarge,
    width: '90%',
    alignSelf: 'center',
    padding: spacing.large,
    backgroundColor: colors.surface,
    borderRadius: spacing.medium + 4,
    elevation: 3,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  imageBox: {
    width: 100,
    height: 100,
    borderRadius: spacing.medium - 4,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.medium,
  },
  nome: {
    color: colors.textPrimary,
    fontSize: typography.fontSizeTitle2 - 1,
    fontWeight: typography.fontWeightBold,
    marginBottom: spacing.small / 2,
  },
  descricao: {
    color: colors.textHint,
    fontSize: typography.fontSizeLabel,
    lineHeight: typography.fontSizeLabel + 6,
  },
  modalText: {
    color: colors.textSecondary,
    fontSize: typography.fontSizeText,
    marginBottom: spacing.large,
    lineHeight: typography.fontSizeText + 6,
    textAlign: 'center',
  },
  infoTextBox: {
    flex: 1,
  },
});
